### ISSUE TITLE
0pen.us 접속이 안 됩니다.

### ISSUE THREAD

**Issue by youngminz** [zer0pen/zer0pen.github.io#5]
현재 사이트 접속이 되고 있지 않습니다. DNS 설정에 문제가 있거나 도메인이 만료된 것 같습니다.

**Comment by grammaright** [comment]
@youngminz 현 회장님께 도메인 이전해드렸음.
저번에 github page에 연결했다고 했는데 잘 안됐나보네..

**Comment by youngminz** [comment]
@grammaright @Erinis에게 연락하여 이슈 해결했습니다. 현재는 접속이 잘 되네요.
